version: "3"
services:
  db:
    image: mariadb:10.4
    environment:
      MYSQL_DATABASE: learnwp
      MYSQL_USER: docker
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - mysql:/var/lib/mysql
  adminer:
    # https://github.com/wodby/docker4wordpress
    image: wodby/adminer
    ports:
      - 8080:9000
  wordpress:
    image: wordpress:latest
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: secret
      WORDPRESS_DB_NAME: learnwp
      DEPLOY_ENVIRONMENT: local
      WORDPRESS_DEBUG: 0
    ports:
      - 80:80
    depends_on:
      - db
    volumes:
      - ./repo/public_html/wp-content:/var/www/html/wp-content
      - ./root:/var/www/html

  wp-cli:
    image: tatemz/wp-cli
    volumes:
      - ./root:/var/www/html
    entrypoint: wp
    command: "--info"

volumes:
  mysql:

